name: WAM APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode
        uses: actions/checkout@v4
      
      - name: Cek Struktur File
        run: ls -R # Ini untuk melihat apakah file kamu sudah masuk ke GitHub

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # Mengunci versi agar stabil
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK Debug
        run: flutter build apk --debug

      - name: Upload Hasil APK
        if: success() # Hanya upload jika build berhasil
        uses: actions/upload-artifact@v4
        with:
          name: APK-Buku-Catatan
          path: build/app/outputs/flutter-apk/app-debug.apk
