name: Build APK Buku Catatan
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create Project and Code
        run: |
          # Membuat proyek flutter baru di dalam mesin GitHub
          flutter create catatan_app --project-name catatan_app --platforms android
          cd catatan_app
          
          # Menulis kode aplikasi buku catatan ke main.dart
          cat <<EOF > lib/main.dart
          import 'package:flutter/material.dart';

          void main() => runApp(MaterialApp(home: CatatanSederhana()));

          class CatatanSederhana extends StatefulWidget {
            @override
            _CatatanSederhanaState createState() => _CatatanSederhanaState();
          }

          class _CatatanSederhanaState extends State<CatatanSederhana> {
            List<String> notes = [];
            final controller = TextEditingController();

            @override
            Widget build(BuildContext context) {
              return Scaffold(
                appBar: AppBar(title: Text("Buku Catatan Maden")),
                body: ListView.builder(
                  itemCount: notes.length,
                  itemBuilder: (context, i) => ListTile(title: Text(notes[i])),
                ),
                bottomSheet: Row(
                  children: [
                    Expanded(child: TextField(controller: controller)),
                    IconButton(icon: Icon(Icons.add), onPressed: () {
                      setState(() { notes.add(controller.text); controller.clear(); });
                    })
                  ],
                ),
              );
            }
          }
          EOF

      - name: Build APK
        run: |
          cd catatan_app
          flutter build apk --debug

      - name: Upload APK ke Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Hasil-APK-Buku-Catatan
          path: catatan_app/build/app/outputs/flutter-apk/app-debug.apk
